branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: redditer
  default_ec2_keyname: null
  default_platform: Ruby 2.2 (Puma)
  default_region: us-east-1
  profile: eb-cli
  sc: git
